'use client';

import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Download, Printer, Share2, FileText, Calendar, User, Clock, CheckCircle } from 'lucide-react';

const reportsData = [
  {
    id: 1,
    title: 'Monthly Patient Statistics',
    type: 'Analytics',
    generatedBy: 'Dr. Michael Chen',
    date: '2024-01-15',
    status: 'completed',
    format: 'PDF',
    size: '2.4 MB',
    pages: 24,
    description: 'Comprehensive analysis of patient admissions, discharges, and bed occupancy rates for January 2024.',
    summary: [
      { label: 'Total Admissions', value: '1,245', change: '+12%' },
      { label: 'Average Stay', value: '4.2 days', change: '-0.5 days' },
      { label: 'Bed Occupancy', value: '87%', change: '+5%' },
      { label: 'Patient Satisfaction', value: '4.6/5', change: '+0.2' }
    ]
  },
];

export default function ReportDetailPage() {
  const params = useParams();
  const report = reportsData.find(r => r.id === parseInt(params.id)) || reportsData[0];

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <Link href="/super-admin/reports" className="inline-flex items-center gap-2 text-sm text-gray-600 hover:text-[#7c3aed] transition-colors">
        <ArrowLeft className="w-4 h-4" />
        Back to Reports
      </Link>

      <div className="bg-white rounded-2xl p-6 shadow-sm">
        <div className="flex flex-col md:flex-row justify-between gap-4 mb-6">
          <div className="flex items-start gap-4">
            <div className="p-4 bg-purple-50 rounded-2xl">
              <FileText className="w-8 h-8 text-[#7c3aed]" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-gray-900">{report.title}</h1>
              <div className="flex items-center gap-3 mt-2">
                <span className="px-2.5 py-1 bg-blue-100 text-blue-700 rounded-lg text-xs font-semibold">
                  {report.type}
                </span>
                <span className="px-2.5 py-1 bg-green-100 text-green-700 rounded-lg text-xs font-semibold">
                  {report.format}
                </span>
              </div>
            </div>
          </div>
          <div className="flex gap-2">
            <button className="flex items-center gap-2 px-4 py-2 border border-gray-200 rounded-xl text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors">
              <Share2 className="w-4 h-4" />
              Share
            </button>
            <button className="flex items-center gap-2 px-4 py-2 bg-[#7c3aed] text-white rounded-xl text-sm font-medium hover:bg-[#6d28d9] transition-colors">
              <Download className="w-4 h-4" />
              Download
            </button>
          </div>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          <div className="p-4 bg-gray-50 rounded-xl">
            <p className="text-xs text-gray-500 mb-1">Generated By</p>
            <p className="text-sm font-semibold text-gray-900">{report.generatedBy}</p>
          </div>
          <div className="p-4 bg-gray-50 rounded-xl">
            <p className="text-xs text-gray-500 mb-1">Date</p>
            <p className="text-sm font-semibold text-gray-900">{report.date}</p>
          </div>
          <div className="p-4 bg-gray-50 rounded-xl">
            <p className="text-xs text-gray-500 mb-1">Size</p>
            <p className="text-sm font-semibold text-gray-900">{report.size}</p>
          </div>
          <div className="p-4 bg-gray-50 rounded-xl">
            <p className="text-xs text-gray-500 mb-1">Pages</p>
            <p className="text-sm font-semibold text-gray-900">{report.pages}</p>
          </div>
        </div>

        <div className="p-4 bg-purple-50 rounded-xl mb-6">
          <h3 className="text-sm font-semibold text-gray-900 mb-4">Executive Summary</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {report.summary.map((item, idx) => (
              <div key={idx} className="text-center">
                <p className="text-lg font-bold text-[#7c3aed]">{item.value}</p>
                <p className="text-xs text-gray-600">{item.label}</p>
                <p className="text-xs text-green-600 mt-1">{item.change}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="prose prose-sm max-w-none">
          <h3 className="text-sm font-semibold text-gray-900 mb-2">Description</h3>
          <p className="text-sm text-gray-600 leading-relaxed">{report.description}</p>
        </div>
      </div>
    </div>
  );
}